export const timerLabel = {
  SESSION: 'sessionLength',
  BREAK: 'breakLength',
};

const TOGGLE_TIMER_RUNNING = 'TOGGLE_TIMER_RUNNING';
const SET_TIMER_IN_PROGRESS = 'SET_TIMER_IN_PROGRESS';
const INCREMENT_TIME = 'INCREMENT_TIME';
const DECREMENT_TIME = 'DECREMENT_TIME';
const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
const SET_NEXT_TIME = 'SET_NEXT_TIME';
const SET_TIMER_LABEL = 'SET_TIMER_LABEL';

export default {
  TOGGLE_TIMER_RUNNING,
  SET_TIMER_IN_PROGRESS,
  INCREMENT_TIME,
  DECREMENT_TIME,
  SET_CURRENT_TIME,
  SET_NEXT_TIME,
  SET_TIMER_LABEL,
};
